name: Build Database

on:
  push:
    branches:
      - main
      - feature/extract-blocker

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lints
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test:unit

      - name: Build Database
        run: pnpm run build-database

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: database
          folder: database
